Here is the updated single-page script using `langchain_huggingface` instead of OpenAI.

Because Hugging Face's local models (`HuggingFacePipeline`) or remote inference endpoints do not always return standardized token usage metadata in the exact same format OpenAI does, this script manually calculates tokens using the model's native tokenizer. This guarantees that your token tracking remains accurate no matter which model you load from the Hugging Face Hub.

### Prerequisites

Make sure you have the required packages installed:

```bash
pip install langchain-huggingface langchain-core transformers torch

```

### Complete Copiable Implementation

```python
import os
from typing import Any, Dict, List
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.outputs import LLMResult
from langchain_core.prompts import ChatPromptTemplate
from langchain_huggingface import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# ==========================================
# 1. THE TOKEN BUDGET TRACKER
# ==========================================
class TokenBudgetExceededError(Exception):
    """Exception raised when the agent consumes more tokens than allowed."""
    pass

class TokenBudget:
    def __init__(self, max_tokens: int):
        self.max_tokens = max_tokens
        self.used_tokens = 0

    def can_spend(self, tokens: int) -> bool:
        return self.used_tokens + tokens <= self.max_tokens

    def spend(self, tokens: int):
        if not self.can_spend(tokens):
            raise TokenBudgetExceededError(
                f"Budget exceeded! Attempted to spend {tokens} tokens, "
                f"but only {self.max_tokens - self.used_tokens} remaining out of {self.max_tokens}."
            )
        self.used_tokens += tokens
        print(f"[TokenBudget] Spent {tokens} tokens. Total used: {self.used_tokens}/{self.max_tokens}")

    @property
    def remaining_tokens(self) -> int:
        return max(0, self.max_tokens - self.used_tokens)


# ==========================================
# 2. HUGGINGFACE BUDGETED CALLBACK HANDLER
# ==========================================
class BudgetedHuggingFaceCallback(BaseCallbackHandler):
    """
    A LangChain callback handler that tokenizes prompt inputs and LLM outputs
    using the model's specific tokenizer to strictly monitor and enforce a budget limit.
    """
    def __init__(self, token_budget: TokenBudget, tokenizer: AutoTokenizer):
        super().__init__()
        self.token_budget = token_budget
        self.tokenizer = tokenizer

    def on_llm_start(self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any) -> Any:
        """Tracks the input tokens sent to the model before it generates."""
        for prompt in prompts:
            input_tokens = len(self.tokenizer.encode(prompt))
            # Enforce budget limits upfront
            self.token_budget.spend(input_tokens)

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> Any:
        """Tracks the output tokens generated by the model."""
        for generations in response.generations:
            for generation in generations:
                generated_text = generation.text
                output_tokens = len(self.tokenizer.encode(generated_text))
                
                # Enforce budget limits on generation output
                self.token_budget.spend(output_tokens)


# ==========================================
# 3. RUNTIME EXECUTABLE EXAMPLE
# ==========================================
if __name__ == "__main__":
    # Choose a lightweight open-source model (e.g., Llama-3.2-1B, Qwen2.5-1.5B, or Phi-3)
    model_id = "Qwen/Qwen2.5-1.5B-Instruct"
    
    print(f"--- Downloading and Loading Model/Tokenizer: {model_id} ---")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")
    
    # Initialize standard Hugging Face Transformers Pipeline
    hf_pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=150,
        temperature=0.7,
        do_sample=True,
    )
    
    # Set a modest token budget to see the guardrail trigger safely
    budget_limit = 250
    print(f"\n--- Initializing TokenBudget with a limit of {budget_limit} tokens ---")
    
    budget = TokenBudget(max_tokens=budget_limit)
    budget_callback = BudgetedHuggingFaceCallback(token_budget=budget, tokenizer=tokenizer)

    # Wrap the transformers pipeline into LangChain
    llm = HuggingFacePipeline(pipeline=hf_pipe, callbacks=[budget_callback])

    prompt = ChatPromptTemplate.from_template("Write a short summary about {topic}.")
    chain = prompt | llm

    try:
        print("\n--- Executing Request 1 ---")
        response_1 = chain.invoke({"topic": "the importance of renewable energy"})
        print(f"\n[Success] Response 1:\n{response_1}")

        print("\n--- Executing Request 2 (Should trigger budget safety) ---")
        response_2 = chain.invoke({"topic": "quantum physics principles explained simply"})
        print(f"\n[Success] Response 2:\n{response_2}")

    except TokenBudgetExceededError as e:
        print(f"\n[Guardrail Triggered] Loop or generation execution safely halted: {e}")

```
